
# curl --location 'https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation'
#--header 'Content-Type: application/json'
#--header "Authorization: Bearer $DASHSCOPE_API_KEY"
#--data '{
#    "model": "qwen-image-max",
#    "input": {
#        "messages": [
#            {
#                "role": "user",
#                "content": [
#                    {
#                        "text": "一副典雅庄重的对联悬挂于厅堂之中，房间是个安静古典的中式布置，桌子上放着一些青花瓷，对联上左书“义本生知人机同道善思新”，右书“通云赋智乾坤启数高志远”， 横批“智启千问”，字体飘逸，在中间挂着一幅中国风的画作，内容是岳阳楼。"
#                    }
#                ]
#            }
#        ]
#    },
#    "parameters": {
#        "negative_prompt": "低分辨率，低画质，肢体畸形，手指畸形，画面过饱和，蜡像感，人脸无细节，过度光滑，画面具有AI感。构图混乱。文字模糊，扭曲。",
#        "prompt_extend": true,
#        "watermark": false,
#        "size": "1664*928"
#    }
#}'
POST https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation
Authorization: Bearer sk-a6d2a8e81419424b9782be0a713724b5
Content-Type: application/json

{
  "model": "qwen-image-max",
  "input": {
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "text": "一副典雅庄重的对联悬挂于厅堂之中，房间是个安静古典的中式布置，桌子上放着一些青花瓷，对联上左书“义本生知人机同道善思新”，右书“通云赋智乾坤启数高志远”， 横批“智启千问”，字体飘逸，在中间挂着一幅中国风的画作，内容是岳阳楼。"
          }
        ]
      }
    ]
  },
  "parameters": {
    "negative_prompt": "低分辨率，低画质，肢体畸形，手指畸形，画面过饱和，蜡像感，人脸无细节，过度光滑，画面具有AI感。构图混乱。文字模糊，扭曲。",
    "prompt_extend": true,
    "watermark": false,
    "size": "1664*928"
  }
}

###
